/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create a group and its initial members in one call. Same idempotency
         *     contract as createEntry: a retry that lands after the original succeeded
         *     returns 200 with the original body.
         */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch a group and its members. */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Current net position of every group member, with the seq they reflect. */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Page the ledger in `seq` order. Poll by passing the highest `seq` seen as
         *     `after_seq`.
         *
         *     `limit` is clamped server-side, not rejected: values below 1 become 100, and
         *     values above 500 become 500.
         */
        get: operations["listEntries"];
        put?: never;
        /**
         * @description Record an expense or settlement.
         *
         *     `Idempotency-Key` is one key per user intent, reused verbatim across retries.
         *     A retry that lands after the original succeeded returns 200 with the original
         *     body; reusing a key with a different payload is 422; a concurrent in-flight
         *     request with the same key is 409 and should be retried shortly.
         */
        post: operations["createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description Edit an entry: reverse the original and append the replacement in one
         *     transaction. The response body is an EditAck, not the full replacement
         *     entry — same as create and reverse, re-read via list-entries to see it.
         */
        put: operations["editEntry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/entries/{entry_id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Reverse an entry. Appends a reversal rather than deleting, so history and
         *     balances stay derivable. Reversing an already-reversed entry is 409.
         */
        post: operations["reverseEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every group member's balance plus the max entry seq those balances reflect.
         *     Both are read in one SQL statement (one MVCC snapshot), so `as_of_seq` is
         *     exactly the ledger state the balances derive from.
         */
        BalanceSnapshot: {
            balances: components["schemas"]["MemberBalance"][];
            /** Format: int64 */
            as_of_seq: number;
        };
        /**
         * Format: date
         * @description Calendar date in `YYYY-MM-DD`.
         */
        CalendarDate: string;
        /**
         * @description What the client sends to record a new entry. `kind: "reversal"` cannot be
         *     created this way — a reversal is always the side effect of the `/reverse`
         *     or edit endpoints, never a direct POST.
         */
        CreateEntryRequest: components["schemas"]["ExpenseEntry"] | components["schemas"]["SettlementEntry"];
        /**
         * @description What the client sends to create a group and its initial members in one
         *     call. `id` is client-generated, same reload-safety rationale as an entry's
         *     id (architecture.md §4): a page reload loses in-flight idempotency-key
         *     state, but the id itself still guards against a duplicate create.
         */
        CreateGroupRequest: {
            id: components["schemas"]["Uuid"];
            name: string;
            member_names: string[];
        };
        /**
         * @description Acknowledgement of an edit. `id`/`seq` are the *replacement* entry, which
         *     reverses nothing and so has no `reverses_id` of its own; `reversal_entry_id`
         *     is the separate reversal that retired the original.
         */
        EditAck: {
            id: components["schemas"]["Uuid"];
            /** Format: int64 */
            seq: number;
            reversal_entry_id: components["schemas"]["Uuid"];
        };
        /**
         * @description Editing is a correction, not a mutation: the original is reversed and a
         *     replacement is appended, so the ledger stays append-only. Same kind-shaped
         *     split as CreateEntryRequest, plus the reversal that retires the original.
         */
        EditEntryRequest: components["schemas"]["ExpenseEdit"] | components["schemas"]["SettlementEdit"];
        /**
         * @description Write acknowledgement. Writes return the new entry's id and the ledger
         *     sequence it was assigned — *not* the full entry. Re-read the ledger via
         *     list-entries to see the record itself; `seq` is the cursor to read from.
         */
        EntryAck: {
            id: components["schemas"]["Uuid"];
            /** Format: int64 */
            seq: number;
        };
        /**
         * @description What kind of movement an entry records.
         * @enum {string}
         */
        EntryKind: "expense" | "settlement" | "reversal";
        EntryList: {
            entries: components["schemas"]["EntryRecord"][];
        };
        /** @description An entry as persisted and returned by the server. */
        EntryRecord: {
            id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Monotonic per-group sequence; the cursor for `after_seq` polling.
             */
            seq: number;
            kind: components["schemas"]["EntryKind"];
            /** @description Set on a reversal entry: the entry it reverses. */
            reverses_id?: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            counterparty?: components["schemas"]["Uuid"];
            /** Format: int64 */
            total_amount: number;
            split_rule: components["schemas"]["SplitRule"];
            participants: components["schemas"]["Uuid"][];
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
            created_by: components["schemas"]["Uuid"];
            /** Format: date-time */
            created_at: string;
            postings: components["schemas"]["Posting"][];
        };
        /** @description Fields every new entry carries regardless of kind. */
        EntryRequestCommon: {
            /** @description Client-generated UUIDv7. Required — the server does not mint entry ids. */
            id: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Minor currency units. Must be in `(0, 100_000_000_000]`.
             */
            total_amount: number;
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
        };
        /** @description Every participant owes the same share; the remainder is distributed deterministically. */
        EqualSplit: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "equal";
        };
        ErrorBody: {
            error: string;
        };
        /** @description Exact minor-unit amount per member, keyed by member id. */
        ExactSplit: {
            amounts: {
                [key: string]: number;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "exact";
        };
        ExpenseEdit: {
            /** @description Client-generated UUIDv7. Required — the server does not mint entry ids. */
            id: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Minor currency units. Must be in `(0, 100_000_000_000]`.
             */
            total_amount: number;
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "expense";
            split_rule: components["schemas"]["SplitRule"];
            /** @description Must be non-empty and free of duplicates. */
            participants: components["schemas"]["Uuid"][];
            reversal_entry_id: components["schemas"]["Uuid"];
        };
        /** @description An expense: `total_amount` is divided among `participants` per `split_rule`. */
        ExpenseEntry: {
            /** @description Client-generated UUIDv7. Required — the server does not mint entry ids. */
            id: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Minor currency units. Must be in `(0, 100_000_000_000]`.
             */
            total_amount: number;
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "expense";
            split_rule: components["schemas"]["SplitRule"];
            /** @description Must be non-empty and free of duplicates. */
            participants: components["schemas"]["Uuid"][];
        };
        /** @description A group and its members, as persisted and returned by the server. */
        GroupRecord: {
            id: components["schemas"]["Uuid"];
            name: string;
            members: components["schemas"]["Member"][];
        };
        Member: {
            id: components["schemas"]["Uuid"];
            name: string;
        };
        /** @description One member's net position: positive = is owed, negative = owes. */
        MemberBalance: {
            member_id: components["schemas"]["Uuid"];
            /** Format: int64 */
            balance: number;
        };
        /** @description Percentage weights per member, keyed by member id. */
        PercentSplit: {
            weights: {
                [key: string]: number;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "percent";
        };
        /** @description One member's signed net amount for an entry. Postings for an entry sum to zero. */
        Posting: {
            member_id: components["schemas"]["Uuid"];
            /** Format: int64 */
            amount: number;
        };
        /** @description Acknowledgement of a reversal, naming the entry it retired. */
        ReversalAck: {
            id: components["schemas"]["Uuid"];
            /** Format: int64 */
            seq: number;
            reverses_id: components["schemas"]["Uuid"];
        };
        ReverseEntryRequest: {
            /** @description Client-generated UUIDv7 for the reversal entry. */
            id: components["schemas"]["Uuid"];
            /** @description Which member is deleting. v1 has no authenticated identity. */
            requested_by: components["schemas"]["Uuid"];
        };
        SettlementEdit: {
            /** @description Client-generated UUIDv7. Required — the server does not mint entry ids. */
            id: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Minor currency units. Must be in `(0, 100_000_000_000]`.
             */
            total_amount: number;
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "settlement";
            /** @description The member being paid. */
            counterparty: components["schemas"]["Uuid"];
            reversal_entry_id: components["schemas"]["Uuid"];
        };
        /**
         * @description A settlement: a direct payment from `payer_id` to `counterparty`, with no
         *     split. The server derives postings and participants from `payer_id` and
         *     `counterparty` alone (addentry.ComputePostings) — `split_rule` does not
         *     apply and is not accepted here.
         */
        SettlementEntry: {
            /** @description Client-generated UUIDv7. Required — the server does not mint entry ids. */
            id: components["schemas"]["Uuid"];
            payer_id: components["schemas"]["Uuid"];
            /**
             * Format: int64
             * @description Minor currency units. Must be in `(0, 100_000_000_000]`.
             */
            total_amount: number;
            memo?: string;
            occurred_on: components["schemas"]["CalendarDate"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "settlement";
            /** @description The member being paid. */
            counterparty: components["schemas"]["Uuid"];
        };
        /** @description Relative weights per member, keyed by member id. */
        SharesSplit: {
            weights: {
                [key: string]: number;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "shares";
        };
        /** @description How an entry's total is divided among its participants. */
        SplitRule: components["schemas"]["EqualSplit"] | components["schemas"]["ExactSplit"] | components["schemas"]["SharesSplit"] | components["schemas"]["PercentSplit"];
        /**
         * Format: uuid
         * @description RFC 9562 UUID. This codebase mints v7 everywhere, so ids are time-ordered.
         */
        Uuid: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createGroup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["schemas"]["Uuid"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /**
             * @description Replay: this `Idempotency-Key` already succeeded, and the body is the
             *     snapshot stored from that original write, byte-identical to what the first
             *     request returned. Not an error — treat as success.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRecord"];
                };
            };
            /** @description The write was accepted and appended to the ledger. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRecord"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupRecord"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSnapshot"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listEntries: {
        parameters: {
            query?: {
                /** @description Exclusive cursor. Absent means from the start of the ledger. */
                after_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                group_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryList"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    createEntry: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["schemas"]["Uuid"];
            };
            path: {
                group_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntryRequest"];
            };
        };
        responses: {
            /**
             * @description Replay: this `Idempotency-Key` already succeeded, and the body is the
             *     snapshot stored from that original write, byte-identical to what the first
             *     request returned. Not an error — treat as success.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryAck"];
                };
            };
            /** @description The write was accepted and appended to the ledger. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryAck"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    editEntry: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["schemas"]["Uuid"];
            };
            path: {
                group_id: components["schemas"]["Uuid"];
                entry_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditEntryRequest"];
            };
        };
        responses: {
            /**
             * @description Replay: this `Idempotency-Key` already succeeded, and the body is the
             *     snapshot stored from that original write, byte-identical to what the first
             *     request returned. Not an error — treat as success.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditAck"];
                };
            };
            /** @description The write was accepted and appended to the ledger. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditAck"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reverseEntry: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["schemas"]["Uuid"];
            };
            path: {
                group_id: components["schemas"]["Uuid"];
                entry_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseEntryRequest"];
            };
        };
        responses: {
            /**
             * @description Replay: this `Idempotency-Key` already succeeded, and the body is the
             *     snapshot stored from that original write, byte-identical to what the first
             *     request returned. Not an error — treat as success.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReversalAck"];
                };
            };
            /** @description The write was accepted and appended to the ledger. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReversalAck"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
