// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (id, group_id, kind, payer_id, counterparty, total_amount,
                     split_rule, participants, memo, occurred_on, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING seq
`

type InsertEntryParams struct {
	ID           uuid.UUID
	GroupID      uuid.UUID
	Kind         string
	PayerID      uuid.UUID
	Counterparty *uuid.UUID
	TotalAmount  int64
	SplitRule    []byte
	Participants []uuid.UUID
	Memo         *string
	OccurredOn   pgtype.Date
	CreatedBy    uuid.UUID
}

// Appends one entry to the ledger, returning the seq assigned by the
// append-only BIGSERIAL. Callers translate a 23505 unique_violation (a
// reused client-generated id) into entry.ErrDuplicateID.
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (*int64, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.ID,
		arg.GroupID,
		arg.Kind,
		arg.PayerID,
		arg.Counterparty,
		arg.TotalAmount,
		arg.SplitRule,
		arg.Participants,
		arg.Memo,
		arg.OccurredOn,
		arg.CreatedBy,
	)
	var seq *int64
	err := row.Scan(&seq)
	return seq, err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (entry_id, member_id, amount)
VALUES ($1, $2, $3)
`

type InsertPostingParams struct {
	EntryID  uuid.UUID
	MemberID uuid.UUID
	Amount   int64
}

// Appends one posting row for an entry. Callers must ensure a whole entry's
// postings sum to zero before calling this query.
func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting, arg.EntryID, arg.MemberID, arg.Amount)
	return err
}
