// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertGroup = `-- name: InsertGroup :exec
INSERT INTO groups (id, name)
VALUES ($1, $2)
`

type InsertGroupParams struct {
	ID   uuid.UUID
	Name string
}

// Appends one group. Callers translate a 23505 unique_violation (a reused
// client-generated id) into group.ErrDuplicateID.
func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) error {
	_, err := q.db.Exec(ctx, insertGroup, arg.ID, arg.Name)
	return err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT INTO group_members (group_id, member_id)
VALUES ($1, $2)
`

type InsertGroupMemberParams struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

// Links a member into a group.
func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertGroupMember, arg.GroupID, arg.MemberID)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO members (id, name)
VALUES ($1, $2)
`

type InsertMemberParams struct {
	ID   uuid.UUID
	Name string
}

// Appends one member. The id is server-minted (uuid.NewV7 — the members
// table has no DB-generated default), unlike a group or entry id.
func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.ID, arg.Name)
	return err
}

const selectGroup = `-- name: SelectGroup :one
SELECT id, name FROM groups WHERE id = $1
`

type SelectGroupRow struct {
	ID   uuid.UUID
	Name string
}

// Fetches a group by id. Callers translate pgx.ErrNoRows into group.ErrNotFound.
func (q *Queries) SelectGroup(ctx context.Context, id uuid.UUID) (SelectGroupRow, error) {
	row := q.db.QueryRow(ctx, selectGroup, id)
	var i SelectGroupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const selectGroupMembers = `-- name: SelectGroupMembers :many
SELECT m.id, m.name
FROM group_members gm
JOIN members m ON m.id = gm.member_id
WHERE gm.group_id = $1
ORDER BY m.id
`

// All members of a group, ordered by member id for a stable response shape.
func (q *Queries) SelectGroupMembers(ctx context.Context, groupID uuid.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, selectGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
