// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deletePendingIdempotencyKey = `-- name: DeletePendingIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE key = $1 AND status = 'pending'
`

// Releases a pending key after a post-gate failure so the client can retry
// immediately. Succeeded keys are never touched: their response is replay truth.
func (q *Queries) DeletePendingIdempotencyKey(ctx context.Context, key uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingIdempotencyKey, key)
	return err
}

const getIdempotencyOutcome = `-- name: GetIdempotencyOutcome :one
SELECT request_hash, status, COALESCE(response_body, 'null'::jsonb) AS response_body
FROM idempotency_keys
WHERE key = $1
`

type GetIdempotencyOutcomeRow struct {
	RequestHash  string
	Status       string
	ResponseBody []byte
}

// Reads the row a conflicting Insert collided with, so the caller can classify
// the acquisition (replay / mismatch / in-flight). COALESCE keeps the body
// non-null for a not-yet-succeeded row.
func (q *Queries) GetIdempotencyOutcome(ctx context.Context, key uuid.UUID) (GetIdempotencyOutcomeRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyOutcome, key)
	var i GetIdempotencyOutcomeRow
	err := row.Scan(&i.RequestHash, &i.Status, &i.ResponseBody)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execrows
INSERT INTO idempotency_keys (key, request_hash, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	Key         uuid.UUID
	RequestHash string
}

// Claims the key with a pending row. ON CONFLICT DO NOTHING means a losing
// racer inserts nothing; the caller reads the affected-row count (:execrows) to
// learn whether it won (1) or must classify an existing row (0).
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepStalePendingIdempotencyKeys = `-- name: SweepStalePendingIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE status = 'pending'
  AND created_at < now() - make_interval(secs => $1::float8)
`

// Janitor sweep: deletes pending rows older than the given age so crashed
// requests can be retried cleanly. Returns the number of rows reclaimed.
func (q *Queries) SweepStalePendingIdempotencyKeys(ctx context.Context, olderThanSecs float64) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStalePendingIdempotencyKeys, olderThanSecs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
