// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: membership.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM group_members
WHERE group_id = $1 AND member_id = ANY($2::uuid[])
`

type CountGroupMembersParams struct {
	GroupID   uuid.UUID
	MemberIds []uuid.UUID
}

// Counts how many of the given member ids belong to the group. Callers compare
// the count against the number of distinct ids they asked about.
func (q *Queries) CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, arg.GroupID, arg.MemberIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}
