// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
	Balance  int64
}

type Entry struct {
	ID           uuid.UUID
	Seq          *int64
	GroupID      uuid.UUID
	Kind         string
	ReversesID   *uuid.UUID
	PayerID      uuid.UUID
	Counterparty *uuid.UUID
	TotalAmount  int64
	SplitRule    []byte
	Participants []uuid.UUID
	PlanSeq      *int64
	Memo         *string
	OccurredOn   pgtype.Date
	CreatedBy    uuid.UUID
	CreatedAt    pgtype.Timestamptz
}

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type GroupMember struct {
	GroupID  uuid.UUID
	MemberID uuid.UUID
}

type IdempotencyKey struct {
	Key          uuid.UUID
	RequestHash  string
	Status       string
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
}

type Member struct {
	ID   uuid.UUID
	Name string
}

type Posting struct {
	EntryID  uuid.UUID
	MemberID uuid.UUID
	Amount   int64
}
