// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Counts how many of the given member ids belong to the group. Callers compare
	// the count against the number of distinct ids they asked about.
	CountGroupMembers(ctx context.Context, arg CountGroupMembersParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
