// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Calendar date in `YYYY-MM-DD`.
 */
export const zCalendarDate = z.iso.date();

/**
 * What kind of movement an entry records.
 */
export const zEntryKind = z.enum([
    'expense',
    'settlement',
    'reversal'
]);

/**
 * Every participant owes the same share; the remainder is distributed deterministically.
 */
export const zEqualSplit = z.record(z.string(), z.unknown());

export const zErrorBody = z.object({
    error: z.string()
});

/**
 * Exact minor-unit amount per member, keyed by member id.
 */
export const zExactSplit = z.object({
    amounts: z.record(z.string(), z.number().int())
});

/**
 * Percentage weights per member, keyed by member id.
 */
export const zPercentSplit = z.object({
    weights: z.record(z.string(), z.number().int())
});

/**
 * Relative weights per member, keyed by member id.
 */
export const zSharesSplit = z.object({
    weights: z.record(z.string(), z.number().int())
});

/**
 * How an entry's total is divided among its participants.
 */
export const zSplitRule = z.union([
    z.object({
        type: z.literal('equal')
    }).and(zEqualSplit),
    z.object({
        type: z.literal('exact')
    }).and(zExactSplit),
    z.object({
        type: z.literal('shares')
    }).and(zSharesSplit),
    z.object({
        type: z.literal('percent')
    }).and(zPercentSplit)
]);

/**
 * RFC 9562 UUID. This codebase mints v7 everywhere, so ids are time-ordered.
 */
export const zUuid = z.uuid();

/**
 * What the client sends to create a group and its initial members in one
 * call. `id` is client-generated, same reload-safety rationale as an entry's
 * id (architecture.md §4): a page reload loses in-flight idempotency-key
 * state, but the id itself still guards against a duplicate create.
 */
export const zCreateGroupRequest = z.object({
    id: zUuid,
    name: z.string(),
    member_names: z.array(z.string())
});

/**
 * Acknowledgement of an edit. `id`/`seq` are the *replacement* entry, which
 * reverses nothing and so has no `reverses_id` of its own; `reversal_entry_id`
 * is the separate reversal that retired the original.
 */
export const zEditAck = z.object({
    id: zUuid,
    seq: z.number().int(),
    reversal_entry_id: zUuid
});

/**
 * Write acknowledgement. Writes return the new entry's id and the ledger
 * sequence it was assigned — *not* the full entry. Re-read the ledger via
 * list-entries to see the record itself; `seq` is the cursor to read from.
 */
export const zEntryAck = z.object({
    id: zUuid,
    seq: z.number().int()
});

/**
 * Fields every new entry carries regardless of kind.
 */
export const zEntryRequestCommon = z.object({
    id: zUuid,
    payer_id: zUuid,
    total_amount: z.number().int(),
    memo: z.string().optional(),
    occurred_on: zCalendarDate
});

export const zExpenseEdit = z.object({
    id: zUuid,
    payer_id: zUuid,
    total_amount: z.number().int(),
    memo: z.string().optional(),
    occurred_on: zCalendarDate,
    kind: z.enum(['expense']),
    split_rule: zSplitRule,
    participants: z.array(zUuid),
    reversal_entry_id: zUuid
});

/**
 * An expense: `total_amount` is divided among `participants` per `split_rule`.
 */
export const zExpenseEntry = z.object({
    id: zUuid,
    payer_id: zUuid,
    total_amount: z.number().int(),
    memo: z.string().optional(),
    occurred_on: zCalendarDate,
    kind: z.enum(['expense']),
    split_rule: zSplitRule,
    participants: z.array(zUuid)
});

export const zMember = z.object({
    id: zUuid,
    name: z.string()
});

/**
 * A group and its members, as persisted and returned by the server.
 */
export const zGroupRecord = z.object({
    id: zUuid,
    name: z.string(),
    members: z.array(zMember)
});

/**
 * One member's net position: positive = is owed, negative = owes.
 */
export const zMemberBalance = z.object({
    member_id: zUuid,
    balance: z.number().int()
});

/**
 * Every group member's balance plus the max entry seq those balances reflect.
 * Both are read in one SQL statement (one MVCC snapshot), so `as_of_seq` is
 * exactly the ledger state the balances derive from.
 */
export const zBalanceSnapshot = z.object({
    balances: z.array(zMemberBalance),
    as_of_seq: z.number().int()
});

/**
 * One member's signed net amount for an entry. Postings for an entry sum to zero.
 */
export const zPosting = z.object({
    member_id: zUuid,
    amount: z.number().int()
});

/**
 * An entry as persisted and returned by the server.
 */
export const zEntryRecord = z.object({
    id: zUuid,
    seq: z.number().int(),
    kind: zEntryKind,
    reverses_id: zUuid.optional(),
    payer_id: zUuid,
    counterparty: zUuid.optional(),
    total_amount: z.number().int(),
    split_rule: zSplitRule,
    participants: z.array(zUuid),
    memo: z.string().optional(),
    occurred_on: zCalendarDate,
    created_by: zUuid,
    created_at: z.iso.datetime(),
    postings: z.array(zPosting)
});

export const zEntryList = z.object({
    entries: z.array(zEntryRecord)
});

/**
 * Acknowledgement of a reversal, naming the entry it retired.
 */
export const zReversalAck = z.object({
    id: zUuid,
    seq: z.number().int(),
    reverses_id: zUuid
});

export const zReverseEntryRequest = z.object({
    id: zUuid,
    requested_by: zUuid
});

export const zSettlementEdit = z.object({
    id: zUuid,
    payer_id: zUuid,
    total_amount: z.number().int(),
    memo: z.string().optional(),
    occurred_on: zCalendarDate,
    kind: z.enum(['settlement']),
    counterparty: zUuid,
    reversal_entry_id: zUuid
});

/**
 * Editing is a correction, not a mutation: the original is reversed and a
 * replacement is appended, so the ledger stays append-only. Same kind-shaped
 * split as CreateEntryRequest, plus the reversal that retires the original.
 */
export const zEditEntryRequest = z.discriminatedUnion('kind', [
    zExpenseEdit.extend({ kind: z.literal('expense') }),
    zSettlementEdit.extend({ kind: z.literal('settlement') })
]);

/**
 * A settlement: a direct payment from `payer_id` to `counterparty`, with no
 * split. The server derives postings and participants from `payer_id` and
 * `counterparty` alone (addentry.ComputePostings) — `split_rule` does not
 * apply and is not accepted here.
 */
export const zSettlementEntry = z.object({
    id: zUuid,
    payer_id: zUuid,
    total_amount: z.number().int(),
    memo: z.string().optional(),
    occurred_on: zCalendarDate,
    kind: z.enum(['settlement']),
    counterparty: zUuid
});

/**
 * What the client sends to record a new entry. `kind: "reversal"` cannot be
 * created this way — a reversal is always the side effect of the `/reverse`
 * or edit endpoints, never a direct POST.
 */
export const zCreateEntryRequest = z.discriminatedUnion('kind', [
    zExpenseEntry.extend({ kind: z.literal('expense') }),
    zSettlementEntry.extend({ kind: z.literal('settlement') })
]);
